[W5.11][F14-A1]Ahmad Syafiq
nus-cs2103-AY1718S2/addressbook-level2 pull request #574
Opened 2018-02-14 17:22 UTC by lithiumlkid

LO-2KLoC

- Find command now ignores case (not case-sensitive). "find john" returns "John"."john","JOHN".
-Updated documentation and tests.

2018-02-15 16:41 UTC, takuyakanbr requested changes
Good work! Some minor style issues with the javadoc comment for the added method.

2018-02-15 16:41 UTC, takuyakanbr commented on src/seedu/addressbook/commands/FindCommand.java
> +     * Changes words into lower case
Javadoc comments, including the tags, should end with a full-stop.

2018-02-15 16:41 UTC, takuyakanbr commented on doc/UserGuide.md
> +> The search is not case sensitive, the order of the keywords does not matter, only the name is searched,
You can consider using 'case insensitive' instead of 'not case sensitive'.

2018-02-18 23:49 UTC, cjianhui reviewed
@lithiumlkid Good job on updating the documentation and tests. Apart from minor issues as mentioned by Siyu, everything else looks fine. 

You may close the PR.

2018-02-23 06:14 UTC, closed without merging